# -*- coding: utf-8 -*-
"""Country name (as used on Liquipedia) -> ISO 3166-1 alpha-2."""
ISO = {
    "Denmark": "DK", "Sweden": "SE", "Norway": "NO", "Finland": "FI",
    "France": "FR", "Germany": "DE", "Poland": "PL", "Czech Republic": "CZ",
    "Czechia": "CZ", "Slovakia": "SK", "United Kingdom": "GB", "Spain": "ES",
    "Portugal": "PT", "Netherlands": "NL", "Belgium": "BE",
    "Bosnia and Herzegovina": "BA", "Serbia": "RS", "Croatia": "HR",
    "Slovenia": "SI", "Montenegro": "ME", "North Macedonia": "MK",
    "Macedonia": "MK", "Bulgaria": "BG", "Romania": "RO", "Hungary": "HU",
    "Austria": "AT", "Switzerland": "CH", "Italy": "IT", "Greece": "GR",
    "Turkey": "TR", "Türkiye": "TR", "Estonia": "EE", "Latvia": "LV",
    "Lithuania": "LT", "Iceland": "IS", "Ireland": "IE", "Luxembourg": "LU",
    "Malta": "MT", "Kosovo": "XK", "Albania": "AL", "Moldova": "MD",
    "Russia": "RU", "Ukraine": "UA", "Belarus": "BY", "Kazakhstan": "KZ",
    "Uzbekistan": "UZ", "Kyrgyzstan": "KG", "Armenia": "AM", "Georgia": "GE",
    "Azerbaijan": "AZ", "Tajikistan": "TJ",
    "United States": "US", "Canada": "CA", "Mexico": "MX", "Brazil": "BR",
    "Argentina": "AR", "Chile": "CL", "Uruguay": "UY", "Peru": "PE",
    "Colombia": "CO", "Venezuela": "VE", "Ecuador": "EC", "Paraguay": "PY",
    "Bolivia": "BO", "Guatemala": "GT", "Costa Rica": "CR",
    "Dominican Republic": "DO",
    "China": "CN", "Mongolia": "MN", "South Korea": "KR", "Japan": "JP",
    "Taiwan": "TW", "Hong Kong": "HK", "Singapore": "SG", "Malaysia": "MY",
    "Indonesia": "ID", "Thailand": "TH", "Vietnam": "VN", "Philippines": "PH",
    "India": "IN", "Pakistan": "PK", "Bangladesh": "BD", "Sri Lanka": "LK",
    "Nepal": "NP", "Myanmar": "MM", "Laos": "LA", "Cambodia": "KH",
    "Macau": "MO",
    "Australia": "AU", "New Zealand": "NZ",
    "Israel": "IL", "Jordan": "JO", "Lebanon": "LB", "Saudi Arabia": "SA",
    "United Arab Emirates": "AE", "Qatar": "QA", "Kuwait": "KW", "Iraq": "IQ",
    "Iran": "IR", "Egypt": "EG", "South Africa": "ZA", "Morocco": "MA",
    "Tunisia": "TN", "Algeria": "DZ", "Nigeria": "NG", "Kenya": "KE",
}
